/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EstadoAsistencia = "AUSENTE" | "JUSTIFICADA" | "PRESENTE" | "TARDE";

export type EstadoCierreMateria = "ABIERTO" | "CERRADO";

export type EstadoColegio = "ACTIVO" | "ELIMINADO" | "PENDIENTE" | "RECHAZADO" | "SUSPENDIDO";

export type EstadoDba = "ACTIVO" | "INACTIVO";

export type EstadoDocumento = "PENDIENTE" | "RECHAZADO" | "VALIDADO";

export type EstadoEstudiante = "ACTIVO" | "EXPULSADO" | "GRADUADO" | "RETIRADO" | "SANCIONADO";

export type EstadoMatricula = "ACTIVA" | "APROBADA" | "CANCELADA" | "CORRECCION" | "CORREGIDA" | "CULMINADA" | "PENDIENTE" | "PENDIENTE_RENOVACION" | "RECHAZADA" | "TRASLADADA";

export type EstadoPeriodo = "ABIERTO" | "CERRADO" | "PENDIENTE";

export type EstadoRenovacionDocumento = "DESACTUALIZADO_POR_FECHA" | "OBLIGATORIO_ACTUALIZAR" | "RECOMENDADO_ACTUALIZAR" | "VIGENTE";

export type EstadoResultado = "APROBADO" | "EN_PROCESO" | "REPROBADO";

export type EstadoSancion = "ACTIVA" | "REVOCADA" | "VENCIDA";

export type EstadoSupervision = "ACTIVA" | "APROBADA" | "EXPIRADA" | "FINALIZADA" | "REVOCADA" | "SOLICITADA";

export type EstadoTicketSoporte = "ABIERTO" | "EN_PROCESO" | "ESCALADO" | "RESUELTO";

export type EstadoUsuarioSistema = "ACTIVO" | "BANEADO" | "ELIMINADO" | "SUSPENDIDO";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TipoAccionAuditoria = "CREACION" | "ELIMINACION" | "EXPORTACION" | "LECTURA" | "MODIFICACION";

export type TipoIncidenciaSoporte = "ASISTENCIA" | "AUTENTICACION" | "CALIFICACIONES" | "MATRICULA_EXTRAORDINARIA" | "REINGRESO" | "SOPORTE" | "TECNICO";

export type TipoJornada = "MAÑANA" | "NOCTURNA" | "TARDE" | "UNICA";

export type TipoMatricula = "EXTRAORDINARIA" | "REGULAR" | "REINGRESO" | "RENOVACION" | "TRASLADO";

export type TipoObservacion = "ACADEMICA" | "CONVIVENCIA" | "DISCIPLINARIA" | "OTRO";

export type TipoSupervision = "EDITOR" | "SOLO_LECTURA";

export interface ActividadEvidenciaDba {
  id_actividadmateria: number;
  id_evidencia_dba: number;
}

export interface ActividadMateria {
  fecha_creacion: Generated<Timestamp | null>;
  id_actividadmateria: Generated<number>;
  id_colegio: number;
  id_competencia: number | null;
  id_detallegrado: number | null;
  id_evidencia: number | null;
  id_periodo: number | null;
  justificacion_extra: string | null;
  motivo_extra: Generated<string | null>;
  nombre: string;
  porcentaje: Numeric;
}

export interface AnioLectivo {
  calendario: string | null;
  estado: Generated<EstadoPeriodo | null>;
  fecha_fin: Timestamp | null;
  fecha_inicio: Timestamp | null;
  id_anio: Generated<number>;
  id_colegio: number;
  tipo_calendario: Generated<string | null>;
}

export interface AuditoriaAccionesRealizadas {
  accion: string;
  fecha_accion: Generated<Timestamp>;
  id_accion: Generated<number>;
  id_auditoria: number;
  id_usuario_afectado: number | null;
  modulo: string;
  motivo_cambio: string | null;
  recurso_afectado: string;
  tipo_accion: TipoAccionAuditoria;
  valor_antiguo: Json | null;
  valor_nuevo: Json | null;
}

export interface AuditoriaSupervision {
  duracion_maxima_minutos: Generated<number>;
  eliminado: Generated<boolean>;
  estado_supervision: Generated<EstadoSupervision>;
  fecha_aprobacion: Timestamp | null;
  fecha_entrada: Timestamp | null;
  fecha_retencion_hasta: Generated<Timestamp>;
  fecha_revocacion: Timestamp | null;
  fecha_salida: Timestamp | null;
  fecha_solicitud: Generated<Timestamp>;
  id_admin_general: number;
  id_auditoria: Generated<number>;
  id_colegio: number;
  id_directivo_aprobador: number | null;
  ip_admin: string | null;
  motivo_entrada: string | null;
  motivo_revocacion: string | null;
  motivo_solicitud: string;
  revocado_por: number | null;
  tipo_supervision: TipoSupervision;
}

export interface CierreMateria {
  estado: EstadoCierreMateria;
  fecha_cierre: Timestamp;
  id_cierremateria: Generated<number>;
  id_detallegrado: number;
  id_periodo: number;
}

export interface Colegio {
  color_primario: Generated<string | null>;
  color_secundario: Generated<string | null>;
  colores: string | null;
  contacto: Numeric;
  correo: string;
  dane: string;
  escudo_url: string | null;
  estado: Generated<EstadoColegio>;
  fecha_cambio_estado: Timestamp | null;
  fecha_registro: Generated<Timestamp>;
  id_colegio: Generated<number>;
  motivo_rechazo: string | null;
  nombre: string;
  sede: string;
  tipo_calendario: Generated<string | null>;
  tipo_colegio: string;
}

export interface ColegioVersionCurricular {
  area: string;
  fecha_asignacion: Generated<Timestamp>;
  grado: string;
  id: Generated<number>;
  id_colegio: number;
  version_curricular: string;
}

export interface Competencias {
  descripcion: Generated<string>;
  id_anio: number;
  id_colegio: number;
  id_competencia: Generated<number>;
  id_dimension: number | null;
  id_grupo: number;
  id_materia: number;
  id_periodo: number;
  nombre: string | null;
  sync_uuid: string | null;
}

export interface ConfiguracionBase {
  clave: string;
  descripcion: string | null;
  id_config_base: Generated<number>;
  tipo: string;
  valor_default: string;
}

export interface ConfiguracionColegio {
  escala_modo: Generated<string>;
  id_colegio: number;
  nota_aprobacion: Generated<Numeric>;
  nota_maxima: Generated<Numeric>;
  nota_minima: Generated<Numeric>;
}

export interface ConfiguracionInscripcion {
  fecha_cierre: Timestamp;
  fecha_inicio: Timestamp;
  habilitada: Generated<boolean>;
  id_anio: number;
  id_colegio: number;
  id_configuracion: Generated<number>;
}

export interface ConfiguracionPlataforma {
  actualizado_por: number | null;
  clave: string;
  descripcion: string | null;
  fecha_actualizacion: Generated<Timestamp>;
  valor: string;
}

export interface ConfiguracionSistema {
  clave: string;
  id_colegio: number;
  id_config_base: number | null;
  id_configuracion: Generated<number>;
  valor: string;
}

export interface ContratoDocente {
  estado: string;
  id_colegio: number;
  id_contratodocente: Generated<number>;
}

export interface CriterioEvaluacion {
  descripcion: string;
  id_actividadmateria: number;
  id_colegio: number;
  id_criterio: Generated<number>;
  id_evidencia: number | null;
  porcentaje: Numeric;
}

export interface Dba {
  area: string;
  created_at: Generated<Timestamp>;
  enunciado: string;
  estado: Generated<EstadoDba>;
  grado: string;
  id_dba: Generated<number>;
  numero_dba: number;
  updated_at: Generated<Timestamp>;
  version_curricular: string;
}

export interface DbaDimensionesPreescolar {
  id_dba: number;
  id_dimension: number;
}

export interface Desempeno {
  descripcion: string;
  id_actividadmateria: number;
  id_colegio: number;
  id_desempeno: Generated<number>;
}

export interface DetalleGrados {
  id_anio: number;
  id_colegio: number;
  id_detallegrado: Generated<number>;
  id_docente: number;
  id_grupo: number | null;
  id_materia: number;
}

export interface DetallePadrefamilia {
  id_colegio: number;
  id_detallepadrefamilia: Generated<number>;
  id_estudiante: number;
  id_padrefamilia: number;
}

export interface DimensionesPreescolar {
  id_dimension: Generated<number>;
  nombre: string;
}

export interface Directivo {
  cargo: string | null;
  estado: Generated<EstadoUsuarioSistema>;
  fecha_desvinculacion: Timestamp | null;
  fecha_vinculacion: Generated<Timestamp>;
  id: Generated<number>;
  id_colegio: number;
  id_usuario: number | null;
}

export interface Docente {
  apellido: string;
  estado: Generated<string>;
  id_colegio: number;
  id_contratodocente: number | null;
  id_docente: Generated<number>;
  id_usuario: number | null;
  nombre: string;
}

export interface DocumentoMatriculas {
  contenido: Buffer | null;
  estado: Generated<EstadoDocumento>;
  estado_renovacion: Generated<EstadoRenovacionDocumento | null>;
  fecha: Timestamp;
  fecha_expedicion: Timestamp | null;
  id_colegio: number;
  id_documento: Generated<number>;
  id_matricula: number;
  mime_type: string | null;
  nombre_original: string | null;
  tamano_bytes: number | null;
  tipo_documento: string;
  url: string;
  version: Generated<number>;
}

export interface EmailChangeTokens {
  codigo: string;
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<number>;
  id_usuario: number | null;
  nuevo_email: string;
  used: Generated<boolean | null>;
}

export interface EscalaValoracion {
  id_colegio: number;
  id_escalavaloracion: Generated<number>;
  nivel: string;
  valor_maximo: Numeric;
  valor_minimo: Numeric;
}

export interface Estudiante {
  apellido: string;
  codigo: string;
  estado: Generated<EstadoEstudiante | null>;
  id_colegio: number;
  id_estudiante: Generated<number>;
  id_nivel: number | null;
  id_usuario: number | null;
  motivo_estado: string | null;
  nombre: string;
}

export interface EvidenciaAprendizaje {
  descripcion: string;
  id_colegio: number;
  id_competencia: number;
  id_evidencia: Generated<number>;
  id_evidencia_dba: number | null;
  orden: Generated<number>;
}

export interface EvidenciasDba {
  created_at: Generated<Timestamp>;
  descripcion: string;
  estado: Generated<EstadoDba>;
  id_dba: number;
  id_evidencia_dba: Generated<number>;
  orden: Generated<number>;
}

export interface Grados {
  cupos_totales: Generated<number>;
  id_colegio: number;
  id_grado: Generated<number>;
  id_jornada: number;
  nivel: string;
  seccion: Generated<string | null>;
  tipo_grado: string;
}

export interface Grupos {
  cupos_totales: Generated<number>;
  id_colegio: number;
  id_docente: number | null;
  id_grupo: Generated<number>;
  id_jornada: number;
  id_nivel: number;
  id_seccion: number;
  id_tipo_grado: number;
}

export interface Jornada {
  id_colegio: number;
  id_jornada: Generated<number>;
  nombre: TipoJornada;
}

export interface Materias {
  id_colegio: number;
  id_materia: Generated<number>;
  nombre: string;
}

export interface Matricula {
  correo_padre: string | null;
  detalles_cancelacion: string | null;
  es_extranjero: Generated<boolean | null>;
  es_traslado: Generated<boolean | null>;
  estado: EstadoMatricula;
  fecha_aprobacion: Timestamp | null;
  fecha_creacion: Generated<Timestamp | null>;
  id_anio: number;
  id_colegio: number;
  id_estudiante: number | null;
  id_grupo: number | null;
  id_matricula: Generated<number>;
  id_nivel: number | null;
  id_ticket: number | null;
  id_usuario_responsable: number | null;
  motivo: string | null;
  motivo_cancelacion: string | null;
  observaciones: string | null;
  tiene_discapacidad: Generated<boolean | null>;
  tipo: Generated<TipoMatricula>;
  token_seguimiento: Generated<string>;
}

export interface NivelEscolar {
  id_colegio: number;
  id_nivel: Generated<number>;
  nombre: string;
}

export interface NotaCriterio {
  id_colegio: number;
  id_criterio: number;
  id_estudiante: number;
  id_nota_criterio: Generated<number>;
  nota: Numeric;
}

export interface NotasActividad {
  id_actividadmateria: number;
  id_colegio: number;
  id_escalavaloracion: number;
  id_estudiante: number;
  id_notaactividad: Generated<number>;
  nota: Numeric;
}

export interface NotificacionColegio {
  estado_anterior: string | null;
  estado_nuevo: string | null;
  fecha_notificacion: Generated<Timestamp>;
  id_colegio: number;
  id_directivo: number;
  id_notificacion: Generated<number>;
  leida: Generated<boolean>;
  mensaje: string;
  tipo: string;
}

export interface NotificacionSupervision {
  fecha_notificacion: Generated<Timestamp>;
  id_auditoria: number;
  id_directivo: number;
  id_notificacion: Generated<number>;
  leida: Generated<boolean>;
  mensaje: string;
  tipo_notificacion: string;
}

export interface ObservacionEstudiante {
  debilidades: string | null;
  fecha: Timestamp;
  fortalezas: string | null;
  id_colegio: number;
  id_detallegrado: number;
  id_estudiante: number;
  id_observacion: Generated<number>;
  id_periodo: number;
  recomendaciones: string | null;
  tipo: Generated<TipoObservacion | null>;
}

export interface PadreFamilia {
  apellido: string;
  id_colegio: number | null;
  id_padrefamilia: Generated<number>;
  id_usuario: number | null;
  nombre: string;
}

export interface PapeleraMaterias {
  data_respaldo: Json | null;
  fecha_borrado: Generated<Timestamp | null>;
  fecha_expiracion: Generated<Timestamp | null>;
  id_colegio: number | null;
  id_papelera: Generated<number>;
  nombre_materia: string | null;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<number>;
  id_usuario: number;
  token: string;
  used: Generated<boolean>;
}

export interface PeriodoAcademico {
  dia_fin: number | null;
  dia_inicio: number | null;
  estado: EstadoPeriodo;
  id_anio: number | null;
  id_colegio: number;
  id_periodo: Generated<number>;
  mes_fin: number | null;
  mes_inicio: number | null;
  nombre: string;
  porcentaje: Numeric;
  trimestre: number | null;
}

export interface RegistroAsistencia {
  estado: Generated<EstadoAsistencia>;
  fecha: Timestamp;
  hora_llegada: string | null;
  id_colegio: number;
  id_detallegrado: number;
  id_estudiante: number;
  id_registroasistencia: Generated<number>;
  justificacion: string | null;
}

export interface RegistroGraduados {
  creado_en: Generated<Timestamp>;
  fecha_graduacion: Generated<Timestamp>;
  id_anio: number | null;
  id_estudiante: number;
  id_graduado: Generated<number>;
  id_usuario_registro: number | null;
  observaciones: string | null;
}

export interface ResultadoAcademico {
  estado: EstadoResultado;
  fecha_cierre: Timestamp;
  id_detallegrado: number;
  id_docente: number;
  id_estudiante: number;
  id_periodo: number;
  id_resultado: Generated<number>;
  observacion: string | null;
  promedio: Numeric;
}

export interface Rol {
  id_rol: Generated<number>;
  nombre: string;
}

export interface Sancion {
  creado_en: Generated<Timestamp | null>;
  estado: Generated<EstadoSancion | null>;
  fecha_fin: Timestamp;
  fecha_inicio: Generated<Timestamp>;
  id_directivo: number;
  id_estudiante: number;
  id_sancion: Generated<number>;
  id_tipo_sancion: number;
  motivo: string;
  observaciones: string | null;
}

export interface Secciones {
  id_seccion: Generated<number>;
  nombre: string;
}

export interface TicketsSoporte {
  asunto: string;
  codigo_ticket: string | null;
  correo_remitente: string;
  descripcion: string;
  estado: Generated<EstadoTicketSoporte | null>;
  fecha_creacion: Generated<Timestamp | null>;
  fecha_escalado: Timestamp | null;
  id_colegio: number | null;
  id_estudiante: number | null;
  id_ticket: Generated<number>;
  id_usuario: number | null;
  nombre_remitente: string;
  observaciones: Generated<Json | null>;
  telefono: string | null;
  tipo_incidencia: TipoIncidenciaSoporte;
}

export interface TipoDocumento {
  id_tipodocumento: Generated<number>;
  tipo: string;
}

export interface TipoGrado {
  id_nivel: number;
  id_tipo_grado: Generated<number>;
  nombre: string;
}

export interface TipoSancion {
  descripcion: string | null;
  id_tipo_sancion: Generated<number>;
  nombre: string;
}

export interface TokenBlacklist {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<number>;
  jti: string;
}

export interface Usuario {
  activo: Generated<boolean | null>;
  apellido: string | null;
  baneado_por: number | null;
  documento: string | null;
  email: string;
  estado: Generated<EstadoUsuarioSistema>;
  fecha_baneo: Timestamp | null;
  fecha_creacion: Generated<Timestamp | null>;
  id_colegio: number | null;
  id_tipodocumento: number | null;
  id_usuario: Generated<number>;
  logged_out_at: Timestamp | null;
  motivo_baneo: string | null;
  nombre: string;
  password: string;
  telefono: string | null;
}

export interface UsuarioRol {
  id_rol: number;
  id_usuario: number;
}

export interface VwAsistenciaEstudiante {
  ausentes: Int8 | null;
  id_detallegrado: number | null;
  id_estudiante: number | null;
  justificadas: Int8 | null;
  presentes: Int8 | null;
  tardes: Int8 | null;
}

export interface VwDesempenoEstudiante {
  "desempeño": string | null;
  id_colegio: number | null;
  id_estudiante: number | null;
  id_periodo: number | null;
  promedio_normalizado: Numeric | null;
}

export interface VwNotasEnriquecidas {
  actividad: string | null;
  apellido: string | null;
  id_colegio: number | null;
  id_detallegrado: number | null;
  id_docente: number | null;
  id_escalavaloracion: number | null;
  id_estudiante: number | null;
  id_materia: number | null;
  id_periodo: number | null;
  nombre: string | null;
  nota: Numeric | null;
}

export interface VwObservacionesEstudiante {
  debilidades: string | null;
  fortalezas: string | null;
  id_estudiante: number | null;
  id_periodo: number | null;
}

export interface VwPromedioEstudiantePeriodo {
  id_colegio: number | null;
  id_estudiante: number | null;
  id_periodo: number | null;
  promedio_raw: Numeric | null;
}

export interface VwPromedioMateria {
  id_colegio: number | null;
  id_estudiante: number | null;
  id_materia: number | null;
  id_periodo: number | null;
  promedio_materia: Numeric | null;
}

export interface VwPromedioNormalizado {
  id_colegio: number | null;
  id_estudiante: number | null;
  id_periodo: number | null;
  promedio_normalizado: Numeric | null;
}

export interface DB {
  actividad_evidencia_dba: ActividadEvidenciaDba;
  actividad_materia: ActividadMateria;
  anio_lectivo: AnioLectivo;
  auditoria_acciones_realizadas: AuditoriaAccionesRealizadas;
  auditoria_supervision: AuditoriaSupervision;
  cierre_materia: CierreMateria;
  colegio: Colegio;
  colegio_version_curricular: ColegioVersionCurricular;
  competencias: Competencias;
  configuracion_base: ConfiguracionBase;
  configuracion_colegio: ConfiguracionColegio;
  configuracion_inscripcion: ConfiguracionInscripcion;
  configuracion_plataforma: ConfiguracionPlataforma;
  configuracion_sistema: ConfiguracionSistema;
  contrato_docente: ContratoDocente;
  criterio_evaluacion: CriterioEvaluacion;
  dba: Dba;
  dba_dimensiones_preescolar: DbaDimensionesPreescolar;
  desempeno: Desempeno;
  detalle_grados: DetalleGrados;
  detalle_padrefamilia: DetallePadrefamilia;
  dimensiones_preescolar: DimensionesPreescolar;
  directivo: Directivo;
  docente: Docente;
  documento_matriculas: DocumentoMatriculas;
  email_change_tokens: EmailChangeTokens;
  escala_valoracion: EscalaValoracion;
  estudiante: Estudiante;
  evidencia_aprendizaje: EvidenciaAprendizaje;
  evidencias_dba: EvidenciasDba;
  grados: Grados;
  grupos: Grupos;
  jornada: Jornada;
  materias: Materias;
  matricula: Matricula;
  nivel_escolar: NivelEscolar;
  nota_criterio: NotaCriterio;
  notas_actividad: NotasActividad;
  notificacion_colegio: NotificacionColegio;
  notificacion_supervision: NotificacionSupervision;
  observacion_estudiante: ObservacionEstudiante;
  padre_familia: PadreFamilia;
  papelera_materias: PapeleraMaterias;
  password_reset_tokens: PasswordResetTokens;
  periodo_academico: PeriodoAcademico;
  registro_asistencia: RegistroAsistencia;
  registro_graduados: RegistroGraduados;
  resultado_academico: ResultadoAcademico;
  rol: Rol;
  sancion: Sancion;
  secciones: Secciones;
  tickets_soporte: TicketsSoporte;
  tipo_documento: TipoDocumento;
  tipo_grado: TipoGrado;
  tipo_sancion: TipoSancion;
  token_blacklist: TokenBlacklist;
  usuario: Usuario;
  usuario_rol: UsuarioRol;
  vw_asistencia_estudiante: VwAsistenciaEstudiante;
  vw_desempeno_estudiante: VwDesempenoEstudiante;
  vw_notas_enriquecidas: VwNotasEnriquecidas;
  vw_observaciones_estudiante: VwObservacionesEstudiante;
  vw_promedio_estudiante_periodo: VwPromedioEstudiantePeriodo;
  vw_promedio_materia: VwPromedioMateria;
  vw_promedio_normalizado: VwPromedioNormalizado;
}
