services:
  frontend:
    container_name: academia-frontend
    image: ghcr.io/danexl24/academia-frontend:latest
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api-academianeiva.adsoproject.dev
    networks:
      - proxy-network
    restart: always

  backend:
    container_name: academia-backend
    image: ghcr.io/danexl24/academia-backend:latest
    build:
      context: ./backend

    environment:
      - TZ=America/Bogota
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - proxy-network
      - academia-internal
    restart: always

  postgres:
    container_name: academia-postgres
    image: postgres:16
    env_file:
      - path: ./backend/.env_postgres
        required: false
    environment:
      - TZ=America/Bogota
      - PGTZ=America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AcademiaNeiva"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - academia-internal
    restart: always

volumes:
  postgres_data:
  uploads_data:

networks:
  proxy-network:
    external: true
  academia-internal:
    driver: bridge
