services:
  frontend:
    container_name: academia-frontend
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api.academianeiva.adsoproject.dev/
    networks:
      - proxy-network
    restart: always

  backend:
    container_name: academia-backend
    build:
      context: ./backend
    environment:
      - TZ=America/Bogota
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=AcademiaNeiva
    env_file:
      - ./backend/.env
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
    networks:
      - proxy-network
      - academia-internal
    restart: always

  postgres:
    container_name: academia-postgres
    image: postgres:16
    env_file:
      - ./backend/.env_postgres
    environment:
      - TZ=America/Bogota
      - PGTZ=America/Bogota
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_scripts:/docker-entrypoint-initdb.d
    networks:
      - academia-internal
    restart: always

volumes:
  postgres_data:
  uploads_data:

networks:
  proxy-network:
    external: true
  academia-internal:
    driver: bridge
