FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache python3 py3-pip make g++ && \
    pip install PyMuPDF psycopg2-binary python-dotenv --break-system-packages

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npx", "ts-node-dev", "--poll", "--respawn", "--transpile-only", "src/server.ts"]
