-- ============================================================================
-- MIGRACIÓN RA01: Panel de Administrador General
-- Fecha: 2026-06-19
-- Descripción: Agrega soporte completo para gestión de colegios por estado,
--              gestión de usuarios con estados granulares, modo supervisión
--              con auditoría completa y sistema de notificaciones.
-- ============================================================================

BEGIN;

-- ============================================================================
-- PASO 1: CREAR NUEVOS ENUMS
-- ============================================================================

DO $$ BEGIN
    CREATE TYPE estado_colegio AS ENUM (
        'PENDIENTE',
        'ACTIVO',
        'SUSPENDIDO',
        'RECHAZADO',
        'ELIMINADO'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE estado_usuario_sistema AS ENUM (
        'ACTIVO',
        'SUSPENDIDO',
        'BANEADO',
        'ELIMINADO'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE tipo_supervision AS ENUM (
        'SOLO_LECTURA',
        'EDITOR'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE estado_supervision AS ENUM (
        'SOLICITADA',
        'APROBADA',
        'ACTIVA',
        'FINALIZADA',
        'REVOCADA',
        'EXPIRADA'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE tipo_accion_auditoria AS ENUM (
        'LECTURA',
        'CREACION',
        'MODIFICACION',
        'ELIMINACION',
        'EXPORTACION'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- PASO 2: ALTERAR TABLA "colegio"
-- Agregar estado, fecha_registro, motivo_rechazo, fecha_cambio_estado
-- ============================================================================

ALTER TABLE colegio
    ADD COLUMN IF NOT EXISTS estado estado_colegio NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN IF NOT EXISTS fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS motivo_rechazo TEXT,
    ADD COLUMN IF NOT EXISTS fecha_cambio_estado TIMESTAMPTZ;

-- Index para búsquedas por estado de colegio
CREATE INDEX IF NOT EXISTS idx_colegio_estado ON colegio (estado);

-- ============================================================================
-- PASO 3: ALTERAR TABLA "usuario"
-- Agregar campo estado (reemplaza activo), motivo_baneo, fecha_baneo, baneado_por
-- ============================================================================

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS estado estado_usuario_sistema NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN IF NOT EXISTS motivo_baneo TEXT,
    ADD COLUMN IF NOT EXISTS fecha_baneo TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS baneado_por INTEGER REFERENCES usuario(id_usuario);

-- Migrar datos existentes: activo=true → ACTIVO, activo=false → SUSPENDIDO
UPDATE usuario SET estado = 'ACTIVO' WHERE activo = TRUE;
UPDATE usuario SET estado = 'SUSPENDIDO' WHERE activo = FALSE;

-- Index para búsquedas por estado de usuario
CREATE INDEX IF NOT EXISTS idx_usuario_estado ON usuario (estado);

-- ============================================================================
-- PASO 4: ALTERAR TABLA "directivo"
-- Agregar estado, fecha_vinculacion, fecha_desvinculacion
-- ============================================================================

ALTER TABLE directivo
    ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN IF NOT EXISTS fecha_vinculacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS fecha_desvinculacion TIMESTAMPTZ;

-- ============================================================================
-- PASO 5: CREAR TABLA "auditoria_supervision"
-- Registro principal de cada sesión de supervisión
-- ============================================================================

CREATE TABLE IF NOT EXISTS auditoria_supervision (
    id_auditoria INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- Quién solicita
    id_admin_general INTEGER NOT NULL REFERENCES usuario(id_usuario),
    -- Sobre qué colegio
    id_colegio INTEGER NOT NULL REFERENCES colegio(id_colegio),
    -- Quién aprueba
    id_directivo_aprobador INTEGER REFERENCES directivo(id),
    -- Solicitud
    motivo_solicitud TEXT NOT NULL,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Tipo y estado
    tipo_supervision tipo_supervision NOT NULL,
    estado_supervision estado_supervision NOT NULL DEFAULT 'SOLICITADA',
    -- Aprobación
    fecha_aprobacion TIMESTAMPTZ,
    -- Entrada/Salida (fecha_salida es nullable porque al entrar aún no existe)
    motivo_entrada TEXT,
    fecha_entrada TIMESTAMPTZ,
    fecha_salida TIMESTAMPTZ,
    -- Duración y expiración
    duracion_maxima_minutos INTEGER NOT NULL DEFAULT 60,
    -- Revocación
    revocado_por INTEGER REFERENCES directivo(id),
    fecha_revocacion TIMESTAMPTZ,
    -- Trazabilidad
    ip_admin VARCHAR(45),
    -- Soft-delete: retención mínima 5 años
    eliminado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_retencion_hasta TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '5 years'),

    PRIMARY KEY (id_auditoria)
);

-- Indexes para consultas frecuentes
CREATE INDEX IF NOT EXISTS idx_audit_sup_admin ON auditoria_supervision (id_admin_general);
CREATE INDEX IF NOT EXISTS idx_audit_sup_colegio ON auditoria_supervision (id_colegio);
CREATE INDEX IF NOT EXISTS idx_audit_sup_estado ON auditoria_supervision (estado_supervision);
CREATE INDEX IF NOT EXISTS idx_audit_sup_fecha ON auditoria_supervision (fecha_solicitud);
CREATE INDEX IF NOT EXISTS idx_audit_sup_eliminado ON auditoria_supervision (eliminado) WHERE eliminado = FALSE;

-- ============================================================================
-- PASO 6: CREAR TABLA "auditoria_acciones_realizadas"
-- Detalle de cada acción durante una supervisión
-- ============================================================================

CREATE TABLE IF NOT EXISTS auditoria_acciones_realizadas (
    id_accion INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- FK a la auditoría padre
    id_auditoria INTEGER NOT NULL REFERENCES auditoria_supervision(id_auditoria),
    -- Cuándo
    fecha_accion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Qué módulo y qué acción
    modulo VARCHAR(255) NOT NULL,
    tipo_accion tipo_accion_auditoria NOT NULL,
    accion VARCHAR(255) NOT NULL,
    -- Recurso afectado (descripción del registro)
    recurso_afectado TEXT NOT NULL,
    -- Usuario afectado (si aplica)
    id_usuario_afectado INTEGER REFERENCES usuario(id_usuario),
    -- Valores antes/después (para modificaciones)
    valor_antiguo JSONB,
    valor_nuevo JSONB,
    -- Motivo del cambio (obligatorio en EDITOR + MODIFICACION)
    motivo_cambio TEXT,

    PRIMARY KEY (id_accion),

    -- CHECK: Si el tipo_accion es MODIFICACION, valor_antiguo, valor_nuevo y motivo_cambio deben ser NOT NULL
    CONSTRAINT chk_modificacion_completa CHECK (
        tipo_accion != 'MODIFICACION' OR (
            valor_antiguo IS NOT NULL AND
            valor_nuevo IS NOT NULL AND
            motivo_cambio IS NOT NULL
        )
    )
);

-- Indexes para consultas frecuentes
CREATE INDEX IF NOT EXISTS idx_audit_acc_auditoria ON auditoria_acciones_realizadas (id_auditoria);
CREATE INDEX IF NOT EXISTS idx_audit_acc_fecha ON auditoria_acciones_realizadas (fecha_accion);
CREATE INDEX IF NOT EXISTS idx_audit_acc_tipo ON auditoria_acciones_realizadas (tipo_accion);
CREATE INDEX IF NOT EXISTS idx_audit_acc_usuario ON auditoria_acciones_realizadas (id_usuario_afectado) WHERE id_usuario_afectado IS NOT NULL;

-- ============================================================================
-- PASO 7: CREAR TABLA "notificacion_supervision"
-- Notificaciones a directivos sobre eventos de supervisión
-- ============================================================================

CREATE TABLE IF NOT EXISTS notificacion_supervision (
    id_notificacion INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_auditoria INTEGER NOT NULL REFERENCES auditoria_supervision(id_auditoria),
    id_directivo INTEGER NOT NULL REFERENCES directivo(id),
    tipo_notificacion VARCHAR(50) NOT NULL,
    mensaje TEXT NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_notificacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id_notificacion)
);

CREATE INDEX IF NOT EXISTS idx_notif_sup_directivo ON notificacion_supervision (id_directivo);
CREATE INDEX IF NOT EXISTS idx_notif_sup_leida ON notificacion_supervision (leida) WHERE leida = FALSE;
CREATE INDEX IF NOT EXISTS idx_notif_sup_auditoria ON notificacion_supervision (id_auditoria);

-- ============================================================================
-- PASO 8: CREAR TABLA "notificacion_colegio"
-- Notificaciones a directivos sobre cambios de estado del colegio
-- ============================================================================

CREATE TABLE IF NOT EXISTS notificacion_colegio (
    id_notificacion INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_colegio INTEGER NOT NULL REFERENCES colegio(id_colegio),
    id_directivo INTEGER NOT NULL REFERENCES directivo(id),
    tipo VARCHAR(50) NOT NULL,
    mensaje TEXT NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo VARCHAR(20),
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_notificacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id_notificacion)
);

CREATE INDEX IF NOT EXISTS idx_notif_col_directivo ON notificacion_colegio (id_directivo);
CREATE INDEX IF NOT EXISTS idx_notif_col_colegio ON notificacion_colegio (id_colegio);
CREATE INDEX IF NOT EXISTS idx_notif_col_leida ON notificacion_colegio (leida) WHERE leida = FALSE;

-- ============================================================================
-- PASO 9: TRIGGER - Proteger auditorías finalizadas
-- Los registros de auditoría no pueden ser modificados ni eliminados
-- una vez que la supervisión ha finalizado, expirado o sido revocada
-- ============================================================================

CREATE OR REPLACE FUNCTION proteger_auditoria_finalizada()
RETURNS TRIGGER AS $$
BEGIN
    -- Bloquear DELETE siempre (soft-delete únicamente)
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Los registros de auditoría no pueden ser eliminados. Use soft-delete.';
    END IF;

    -- Bloquear UPDATE si la auditoría ya fue finalizada/revocada/expirada
    IF TG_OP = 'UPDATE' THEN
        IF OLD.estado_supervision IN ('FINALIZADA', 'REVOCADA', 'EXPIRADA') THEN
            -- Permitir solo actualizar el campo "eliminado" para soft-delete
            IF NEW.eliminado IS DISTINCT FROM OLD.eliminado AND
               NEW.id_auditoria = OLD.id_auditoria AND
               NEW.estado_supervision = OLD.estado_supervision THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'No se puede modificar una auditoría en estado %', OLD.estado_supervision;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_proteger_auditoria
    BEFORE UPDATE OR DELETE ON auditoria_supervision
    FOR EACH ROW
    EXECUTE FUNCTION proteger_auditoria_finalizada();

-- Trigger para proteger acciones de auditorías finalizadas
CREATE OR REPLACE FUNCTION proteger_acciones_auditoria()
RETURNS TRIGGER AS $$
DECLARE
    v_estado estado_supervision;
BEGIN
    -- Obtener el estado de la auditoría padre
    SELECT estado_supervision INTO v_estado
    FROM auditoria_supervision
    WHERE id_auditoria = COALESCE(OLD.id_auditoria, NEW.id_auditoria);

    IF v_estado IN ('FINALIZADA', 'REVOCADA', 'EXPIRADA') THEN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'No se pueden eliminar acciones de una auditoría finalizada';
        END IF;
        IF TG_OP = 'UPDATE' THEN
            RAISE EXCEPTION 'No se pueden modificar acciones de una auditoría finalizada';
        END IF;
    END IF;

    -- Bloquear DELETE siempre (las acciones de auditoría nunca se eliminan)
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Los registros de acciones de auditoría no pueden ser eliminados';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_proteger_acciones
    BEFORE UPDATE OR DELETE ON auditoria_acciones_realizadas
    FOR EACH ROW
    EXECUTE FUNCTION proteger_acciones_auditoria();

-- ============================================================================
-- PASO 10: INSERTAR ROL "Admin General" SI NO EXISTE
-- ============================================================================

INSERT INTO rol (nombre) VALUES ('admin_general')
ON CONFLICT (nombre) DO NOTHING;

COMMIT;
