export interface ModuleSummary {
  id: string;
  num: string;
  name: string;
  shortName: string;
  domain: string;
  icon: string;
  purpose: string;
  description: string;
  roles: string[];
  dependsOn: string[];
  affects: string[];
  tables: string[];
  rules: string[];
  hus: string[];
  status: 'CONSOLIDADO' | 'EN_EVOLUCION' | 'ESTABLE';
  connectionsCount: number;
}

export interface SystemMetrics {
  totalModules: number;
  totalTables: number;
  totalGlobalRules: number;
  totalAdrs: number;
  totalDomains: number;
  documentationCoveragePercent: number;
  mostConnectedModules: { name: string; id: string; count: number }[];
  domainDistribution: { domain: string; count: number; color: string }[];
}

export const MODULES_METADATA: Record<string, ModuleSummary> = {
  maestro: {
    id: "maestro",
    num: "00",
    name: "🏛️ Maestro de Información del Sistema",
    shortName: "Documento Rector",
    domain: "Gobernanza Global y Arquitectura",
    icon: "Landmark",
    purpose: "Documento rector que consolida la visión global, glosario canónico, arquitectura de negocio y 34 reglas transversales.",
    description: "Capa superior de inteligencia de negocio y gobernanza transversal que articula los 21 módulos del sistema, garantizando consistencia, inmutabilidad y cumplimiento de normativas del MEN (Ley 115, Dec 1290, Dec 1075).",
    roles: ["Todos los Roles", "Administrador General", "Directivo", "Auditor"],
    dependsOn: [],
    affects: ["01_autenticacion", "02_gestion_colegios", "03_usuarios_y_directivos", "04_estructura_escolar", "05_docentes", "06_matriculas", "07_estudiantes_y_estados", "08_configuracion_academica", "09_competencias_y_sincronizacion", "10_catalogo_dba", "11_calificaciones", "12_observaciones", "13_asistencia", "14_cierre_y_boletines", "15_supervision_y_auditoria", "16_soporte_y_tickets", "17_gestion_padres", "18_gestion_traslados", "19_seguimiento_y_promocion_academica", "20_seguimiento_academico_directivo", "21_flujo_correos_y_verificaciones"],
    tables: ["Todas las 62 tablas del sistema"],
    rules: ["RN-GLOBAL-001 a RN-GLOBAL-034", "ADR-001 a ADR-011"],
    hus: ["Todas las Historias de Usuario"],
    status: "CONSOLIDADO",
    connectionsCount: 21
  },
  "01_autenticacion": {
    id: "01_autenticacion",
    num: "01",
    name: "🔐 01. Autenticación y Sesiones",
    shortName: "Autenticación",
    domain: "Identidad, Seguridad y Acceso",
    icon: "Lock",
    purpose: "Centralizar el inicio de sesión unificado, emisión de JWTs con jti, control de estados de cuenta y listas negras.",
    description: "Punto de entrada de seguridad para los 5 roles del sistema. Valida credenciales, comprueba el estado activo del usuario y de su colegio, y maneja revocaciones forzadas de sesión mediante token_blacklist y logged_out_at.",
    roles: ["Administrador General", "Directivo", "Docente", "Padre de Familia", "Estudiante"],
    dependsOn: ["02_gestion_colegios", "03_usuarios_y_directivos"],
    affects: ["05_docentes", "06_matriculas", "07_estudiantes_y_estados", "15_supervision_y_auditoria", "17_gestion_padres", "20_seguimiento_academico_directivo"],
    tables: ["usuario", "rol", "usuario_rol", "usuario_colegio", "token_blacklist"],
    rules: ["RN-GLOBAL-001", "RN-GLOBAL-002", "RN-GLOBAL-003", "RN-GLOBAL-005", "RN-GLOBAL-010", "RN-GLOBAL-026", "RN-AUT-001 a RN-AUT-007"],
    hus: ["HU-AUT-001", "HU-AUT-002", "HU-AUT-003", "HU-AUT-004", "HU-AUT-005", "HU-AUT-006"],
    status: "CONSOLIDADO",
    connectionsCount: 14
  },
  "02_gestion_colegios": {
    id: "02_gestion_colegios",
    num: "02",
    name: "🏫 02. Gestión de Colegios",
    shortName: "Colegios",
    domain: "Gobierno Institucional",
    icon: "Building",
    purpose: "Administrar el catálogo de instituciones educativas y la personalización de identidad visual (branding y escudo).",
    description: "Gobierno multi-tenant de instituciones educativas. Permite al Administrador General registrar y aprobar colegios, y a los directivos configurar sus escudos, colores corporativos y parámetros de funcionamiento.",
    roles: ["Administrador General", "Directivo"],
    dependsOn: ["01_autenticacion"],
    affects: ["03_usuarios_y_directivos", "04_estructura_escolar", "06_matriculas", "08_configuracion_academica", "15_supervision_y_auditoria", "18_gestion_traslados"],
    tables: ["colegio", "configuracion_colegio", "configuracion_sistema"],
    rules: ["RN-GLOBAL-001", "RN-GLOBAL-003", "RN-GLOBAL-022", "RN-COL-001 a RN-COL-006"],
    hus: ["HU-COL-001", "HU-COL-002", "HU-COL-003", "HU-COL-004", "HU-COL-005"],
    status: "CONSOLIDADO",
    connectionsCount: 12
  },
  "03_usuarios_y_directivos": {
    id: "03_usuarios_y_directivos",
    num: "03",
    name: "👥 03. Usuarios y Directivos",
    shortName: "Usuarios",
    domain: "Identidad, Seguridad y Acceso",
    icon: "Users",
    purpose: "Administrar las cuentas de personal directivo, asignación de roles y control de credenciales institucionales.",
    description: "Centraliza el gobierno de directivos escolares (Rectores, Coordinadores) y la trazabilidad de modificaciones de credenciales exigiendo tickets de soporte resueltos.",
    roles: ["Administrador General", "Directivo"],
    dependsOn: ["01_autenticacion", "02_gestion_colegios", "16_soporte_y_tickets"],
    affects: ["04_estructura_escolar", "05_docentes", "06_matriculas", "15_supervision_y_auditoria", "20_seguimiento_academico_directivo"],
    tables: ["usuario", "directivo", "usuario_rol", "usuario_colegio"],
    rules: ["RN-GLOBAL-004", "RN-GLOBAL-005", "RN-GLOBAL-006", "RN-GLOBAL-008", "RN-GLOBAL-011", "RN-DIR-001 a RN-DIR-008"],
    hus: ["HU-DIR-001", "HU-DIR-002", "HU-DIR-003", "HU-DIR-004", "HU-DIR-005", "HU-DIR-006"],
    status: "CONSOLIDADO",
    connectionsCount: 11
  },
  "04_estructura_escolar": {
    id: "04_estructura_escolar",
    num: "04",
    name: "🏗️ 04. Estructura Escolar",
    shortName: "Estructura Escolar",
    domain: "Gobierno Institucional",
    icon: "Network",
    purpose: "Modelar los niveles educativos, tipos de grado, jornadas, salones con control de cupos y catálogo de asignaturas.",
    description: "Organización física y pedagógica del plantel conforme a la Ley 115 (Preescolar, Primaria, Secundaria, Media). Controla la disponibilidad de cupos en grupos y la malla curricular institucional.",
    roles: ["Directivo"],
    dependsOn: ["02_gestion_colegios"],
    affects: ["05_docentes", "06_matriculas", "08_configuracion_academica", "09_competencias_y_sincronizacion", "11_calificaciones", "18_gestion_traslados"],
    tables: ["nivel_escolar", "tipo_grado", "jornada", "secciones", "grados", "grupos", "materias"],
    rules: ["RN-GLOBAL-015", "RN-GLOBAL-030", "RN-GLOBAL-033", "RN-EST-001 a RN-EST-008"],
    hus: ["HU-EST-001", "HU-EST-002", "HU-EST-003", "HU-EST-004", "HU-EST-005"],
    status: "CONSOLIDADO",
    connectionsCount: 13
  },
  "05_docentes": {
    id: "05_docentes",
    num: "05",
    name: "👩‍🏫 05. Docentes y Asignación Académica",
    shortName: "Docentes",
    domain: "Gobierno Institucional",
    icon: "GraduationCap",
    purpose: "Registrar la planta profesoral, validar datos de contacto telefónico y asignar cargas en detalle_grados.",
    description: "Vinculación de profesores al colegio, formalización de la carga académica (Materia × Docente × Grupo × Año) y despacho automático de credenciales iniciales por correo.",
    roles: ["Directivo", "Docente"],
    dependsOn: ["01_autenticacion", "03_usuarios_y_directivos", "04_estructura_escolar", "21_flujo_correos_y_verificaciones"],
    affects: ["09_competencias_y_sincronizacion", "11_calificaciones", "12_observaciones", "13_asistencia", "14_cierre_y_boletines", "20_seguimiento_academico_directivo"],
    tables: ["docente", "usuario", "detalle_grados", "contrato_docente"],
    rules: ["RN-GLOBAL-004", "RN-GLOBAL-006", "RN-GLOBAL-015", "RN-GLOBAL-027", "RN-DOC-001 a RN-DOC-006"],
    hus: ["HU-DOC-001", "HU-DOC-002", "HU-DOC-003", "HU-DOC-004", "HU-DOC-005"],
    status: "CONSOLIDADO",
    connectionsCount: 15
  },
  "06_matriculas": {
    id: "06_matriculas",
    num: "06",
    name: "📋 06. Matrículas e Inscripciones",
    shortName: "Matrículas",
    domain: "Admisión y Movilidad Estudiantil",
    icon: "ClipboardList",
    purpose: "Gestionar el ciclo de vida de matrícula (tipos REGULAR, EXTRAORDINARIA, REINGRESO, RENOVACION, TRASLADO), máquina de estados (PENDIENTE a ACTIVA), verificación OTP, matriz documental y formalización atómica.",
    description: "Puerta de entrada de alumnos al colegio. Coordina la máquina de estados de matrícula, verificación OTP de acudientes, enlaces UUID con bypass de calendario para matrículas extraordinarias y de reingreso, matriz documental inteligente y alta atómica de estudiantes y familias.",
    roles: ["Público / Aspirante", "Padre de Familia", "Directivo", "Administrador General"],
    dependsOn: ["01_autenticacion", "02_gestion_colegios", "04_estructura_escolar", "16_soporte_y_tickets", "21_flujo_correos_y_verificaciones"],
    affects: ["07_estudiantes_y_estados", "11_calificaciones", "13_asistencia", "15_supervision_y_auditoria", "17_gestion_padres", "18_gestion_traslados", "19_seguimiento_y_promocion_academica"],
    tables: ["matricula", "documento_matriculas", "configuracion_inscripcion", "estudiante", "padre_familia", "detalle_padrefamilia", "codigo_verificacion_email"],
    rules: ["RN-GLOBAL-001", "RN-GLOBAL-006", "RN-GLOBAL-014", "RN-GLOBAL-023", "RN-GLOBAL-027", "RN-MAT-001 a RN-MAT-018", "RN-MAIL-001"],
    hus: ["HU-MAT-001", "HU-MAT-002", "HU-MAT-003", "HU-MAT-004", "HU-MAT-005", "HU-MAT-006", "HU-MAT-007", "HU-MAT-008"],
    status: "CONSOLIDADO",
    connectionsCount: 17
  },
  "07_estudiantes_y_estados": {
    id: "07_estudiantes_y_estados",
    num: "07",
    name: "🎓 07. Estudiantes y Estados",
    shortName: "Estudiantes",
    domain: "Admisión y Movilidad Estudiantil",
    icon: "UserCheck",
    purpose: "Administrar la trayectoria vital del alumno, estados disciplinarios y portales de consulta.",
    description: "Monitoreo del ciclo vital del educando (ACTIVO, SANCIONADO, EXPULSADO, RETIRADO, GRADUADO) y sincronización automática del estado mediante triggers SQL de sanciones disciplinarias.",
    roles: ["Directivo", "Estudiante", "Padre de Familia"],
    dependsOn: ["06_matriculas"],
    affects: ["11_calificaciones", "12_observaciones", "13_asistencia", "14_cierre_y_boletines", "17_gestion_padres", "18_gestion_traslados", "19_seguimiento_y_promocion_academica"],
    tables: ["estudiante", "usuario", "sancion", "tipo_sancion", "registro_graduados"],
    rules: ["RN-GLOBAL-004", "RN-GLOBAL-011", "RN-GLOBAL-018", "RN-GLOBAL-023", "RN-STU-001 a RN-STU-006"],
    hus: ["HU-STU-001", "HU-STU-002", "HU-STU-003", "HU-STU-004", "HU-STU-005"],
    status: "CONSOLIDADO",
    connectionsCount: 14
  },
  "08_configuracion_academica": {
    id: "08_configuracion_academica",
    num: "08",
    name: "⚙️ 08. Configuración Académica",
    shortName: "Config. Académica",
    domain: "Gobierno Institucional",
    icon: "Sliders",
    purpose: "Parametrizar años lectivos, periodos académicos y escalas de evaluación del SIEE.",
    description: "Gobernanza del calendario institucional. Controla la apertura/cierre de años escolares, periodos ponderados porcentualmente y la activación de triggers de inmutabilidad en periodos cerrados.",
    roles: ["Directivo"],
    dependsOn: ["02_gestion_colegios"],
    affects: ["06_matriculas", "09_competencias_y_sincronizacion", "11_calificaciones", "13_asistencia", "14_cierre_y_boletines", "19_seguimiento_y_promocion_academica"],
    tables: ["anio_lectivo", "periodo_academico", "escala_valoracion", "configuracion_colegio"],
    rules: ["RN-GLOBAL-012", "RN-GLOBAL-013", "RN-GLOBAL-019", "RN-GLOBAL-031", "RN-CONF-001 a RN-CONF-008"],
    hus: ["HU-CON-001", "HU-CON-002", "HU-CON-003", "HU-CON-004", "HU-CON-005", "HU-CON-006", "HU-CON-007"],
    status: "CONSOLIDADO",
    connectionsCount: 14
  },
  "09_competencias_y_sincronizacion": {
    id: "09_competencias_y_sincronizacion",
    num: "09",
    name: "🔄 09. Competencias y Sincronización",
    shortName: "Competencias",
    domain: "Currículo y Calidad Pedagógica",
    icon: "RefreshCw",
    purpose: "Diseñar la planeación curricular periódica y propagar metas a cursos paralelos vía sync_uuid.",
    description: "Estructuración de metas de aprendizaje por materia y periodo. Cuenta con sincronización en caliente para salones paralelos del mismo grado y tratamiento pedagógico especial para dimensiones de preescolar.",
    roles: ["Directivo", "Docente"],
    dependsOn: ["04_estructura_escolar", "05_docentes", "08_configuracion_academica", "10_catalogo_dba"],
    affects: ["11_calificaciones", "14_cierre_y_boletines"],
    tables: ["competencias", "evidencia_aprendizaje", "actividad_materia"],
    rules: ["RN-GLOBAL-015", "RN-GLOBAL-027", "RN-COMP-001 a RN-COMP-006"],
    hus: ["HU-COM-001", "HU-COM-002", "HU-COM-003", "HU-COM-004"],
    status: "CONSOLIDADO",
    connectionsCount: 10
  },
  "10_catalogo_dba": {
    id: "10_catalogo_dba",
    num: "10",
    name: "📚 10. Catálogo DBA y Coherencia Curricular",
    shortName: "Catálogo DBA",
    domain: "Currículo y Calidad Pedagógica",
    icon: "BookOpen",
    purpose: "Alinear la planeación docente con los Derechos Básicos de Aprendizaje oficiales del MEN.",
    description: "Repositorio nacional de DBA por área y grado. Permite a los docentes vincular evidencias 1-to-1 y genera reportes directivos de coherencia curricular y cobertura temática.",
    roles: ["Administrador General", "Directivo", "Docente"],
    dependsOn: ["02_gestion_colegios"],
    affects: ["09_competencias_y_sincronizacion", "11_calificaciones"],
    tables: ["dba", "evidencias_dba", "colegio_version_curricular", "actividad_evidencia_dba", "dimensiones_preescolar"],
    rules: ["RN-DBA-001 a RN-DBA-006"],
    hus: ["HU-DBA-001", "HU-DBA-002", "HU-DBA-003", "HU-DBA-004", "HU-DBA-005"],
    status: "CONSOLIDADO",
    connectionsCount: 9
  },
  "11_calificaciones": {
    id: "11_calificaciones",
    num: "11",
    name: "📊 11. Calificaciones y Actividades",
    shortName: "Calificaciones",
    domain: "Evaluación Continua y Rendimiento",
    icon: "BarChart3",
    purpose: "Evaluar el rendimiento continuo mediante actividades ponderadas y criterios evaluativos.",
    description: "Planilla docente interactiva. Permite crear actividades, asignar rúbricas porcentuales, calcular promedios parciales y traducir a la escala cualitativa nacional (Superior, Alto, Básico, Bajo).",
    roles: ["Docente", "Estudiante", "Padre de Familia", "Directivo"],
    dependsOn: ["04_estructura_escolar", "05_docentes", "06_matriculas", "08_configuracion_academica", "09_competencias_y_sincronizacion"],
    affects: ["14_cierre_y_boletines", "19_seguimiento_y_promocion_academica", "20_seguimiento_academico_directivo"],
    tables: ["actividad_materia", "notas_actividad", "criterio_evaluacion", "nota_criterio", "desempeno"],
    rules: ["RN-GLOBAL-015", "RN-GLOBAL-016", "RN-GLOBAL-019", "RN-GLOBAL-020", "RN-GLOBAL-031", "RN-CAL-001 a RN-CAL-006"],
    hus: ["HU-CAL-001", "HU-CAL-002", "HU-CAL-003", "HU-CAL-004", "HU-CAL-005"],
    status: "CONSOLIDADO",
    connectionsCount: 15
  },
  "12_observaciones": {
    id: "12_observaciones",
    num: "12",
    name: "📝 12. Observaciones del Estudiante",
    shortName: "Observador",
    domain: "Evaluación Continua y Rendimiento",
    icon: "FileSignature",
    purpose: "Llevar el seguimiento formativo y comportamental en el Observador del Alumno.",
    description: "Registro de anotaciones formativas categorizadas (Académica, Convivencia, Disciplinaria, Otro) con obligatoriedad de la anotación académica para su impresión en boletines oficiales.",
    roles: ["Docente", "Directivo", "Padre de Familia"],
    dependsOn: ["05_docentes", "06_matriculas", "08_configuracion_academica"],
    affects: ["14_cierre_y_boletines", "20_seguimiento_academico_directivo"],
    tables: ["observacion_estudiante"],
    rules: ["RN-GLOBAL-019", "RN-GLOBAL-020", "RN-GLOBAL-030", "RN-OBS-001 a RN-OBS-005"],
    hus: ["HU-OBS-001", "HU-OBS-002", "HU-OBS-003", "HU-OBS-004"],
    status: "CONSOLIDADO",
    connectionsCount: 9
  },
  "13_asistencia": {
    id: "13_asistencia",
    num: "13",
    name: "📅 13. Asistencia Escolar",
    shortName: "Asistencia",
    domain: "Evaluación Continua y Rendimiento",
    icon: "CalendarCheck",
    purpose: "Controlar la asistencia diaria con límite físico de 7 bloques de clase al día.",
    description: "Toma diaria de asistencia por parte de docentes con estados PRESENTE, AUSENTE, TARDE y JUSTIFICADA. Bloqueo estricto que prohíbe registrar más de 7 horas diarias por estudiante.",
    roles: ["Docente", "Padre de Familia", "Directivo"],
    dependsOn: ["05_docentes", "06_matriculas", "08_configuracion_academica"],
    affects: ["14_cierre_y_boletines", "19_seguimiento_y_promocion_academica", "20_seguimiento_academico_directivo"],
    tables: ["registro_asistencia"],
    rules: ["RN-GLOBAL-019", "RN-GLOBAL-020", "RN-ASI-001 a RN-ASI-005"],
    hus: ["HU-ASI-001", "HU-ASI-002", "HU-ASI-003", "HU-ASI-004"],
    status: "CONSOLIDADO",
    connectionsCount: 10
  },
  "14_cierre_y_boletines": {
    id: "14_cierre_y_boletines",
    num: "14",
    name: "📄 14. Cierre y Boletines Oficiales",
    shortName: "Cierre y Boletines",
    domain: "Evaluación Continua y Rendimiento",
    icon: "FileText",
    purpose: "Consolidar notas por materia, ejecutar el cierre de periodo y emitir boletines oficiales en PDF e informes parciales de traslado.",
    description: "Cierre escalonado en 2 niveles: Cierre por Asignatura del profesor y Cierre Institucional del Periodo con renderizado de boletines PDF inmutables. Incluye generador de Certificado Parcial de Traslado a la fecha de retiro (Decreto 1075 de 2015 Art. 2.3.3.3.3.17).",
    roles: ["Docente", "Directivo", "Estudiante", "Padre de Familia"],
    dependsOn: ["08_configuracion_academica", "11_calificaciones", "12_observaciones", "13_asistencia"],
    affects: ["18_gestion_traslados", "19_seguimiento_y_promocion_academica", "20_seguimiento_academico_directivo"],
    tables: ["cierre_materia", "resultado_academico", "periodo_academico", "escala_valoracion"],
    rules: ["RN-GLOBAL-019", "RN-GLOBAL-020", "RN-GLOBAL-025", "RN-BOL-001 a RN-BOL-006", "Decreto 1075 Art. 2.3.3.3.3.17"],
    hus: ["HU-BOL-001", "HU-BOL-002", "HU-BOL-003", "HU-BOL-004", "HU-BOL-005"],
    status: "CONSOLIDADO",
    connectionsCount: 14
  },
  "15_supervision_y_auditoria": {
    id: "15_supervision_y_auditoria",
    num: "15",
    name: "🕵️ 15. Supervisión y Auditoría",
    shortName: "Supervisión",
    domain: "Auditoría, Gobernanza y Soporte",
    icon: "ShieldAlert",
    purpose: "Auditar accesos extraordinarios del Administrador General mediante deltas JSONB inmutables.",
    description: "Supervisión extraordinaria con re-autenticación obligatoria por contraseña del Rector, sesión máxima de 60 minutos, filtro por año lectivo y bitácora legal inmutable (DELETE prohibido por trigger SQL).",
    roles: ["Administrador General", "Directivo"],
    dependsOn: ["01_autenticacion", "02_gestion_colegios", "03_usuarios_y_directivos"],
    affects: ["Todos los módulos auditados"],
    tables: ["auditoria_supervision", "auditoria_acciones_realizadas", "notificacion_supervision"],
    rules: ["RN-GLOBAL-002", "RN-GLOBAL-025", "RN-GLOBAL-033", "RN-SUP-001 a RN-SUP-008"],
    hus: ["HU-SUP-001", "HU-SUP-002", "HU-SUP-003", "HU-SUP-004", "HU-SUP-005", "HU-SUP-006", "HU-SUP-007", "HU-SUP-008"],
    status: "CONSOLIDADO",
    connectionsCount: 11
  },
  "16_soporte_y_tickets": {
    id: "16_soporte_y_tickets",
    num: "16",
    name: "🎟️ 16. Soporte y Mesa de Ayuda",
    shortName: "Soporte",
    domain: "Auditoría, Gobernanza y Soporte",
    icon: "LifeBuoy",
    purpose: "Atender incidencias públicas e institucionales mediante código Base36 y regla de turnos ping-pong.",
    description: "Mesa de ayuda con códigos públicos ofuscados (TKT-XXXX), selector interactivo de estados, regla de alternancia de respuestas para prevenir spam y escalamiento exclusivo al Admin General.",
    roles: ["Todos los Roles", "Público", "Administrador General", "Directivo"],
    dependsOn: ["01_autenticacion", "02_gestion_colegios"],
    affects: ["03_usuarios_y_directivos", "06_matriculas", "07_estudiantes_y_estados", "15_supervision_y_auditoria"],
    tables: ["tickets_soporte", "mensajes_ticket"],
    rules: ["RN-GLOBAL-021", "RN-GLOBAL-030", "RN-SOP-001 a RN-SOP-006"],
    hus: ["HU-SOP-001", "HU-SOP-002", "HU-SOP-003", "HU-SOP-004", "HU-SOP-005"],
    status: "CONSOLIDADO",
    connectionsCount: 9
  },
  "17_gestion_padres": {
    id: "17_gestion_padres",
    num: "17",
    name: "👨‍👩‍👧‍👦 17. Gestión de Padres de Familia",
    shortName: "Gestión Padres",
    domain: "Admisión y Movilidad Estudiantil",
    icon: "HeartHandshake",
    purpose: "Consola directiva para auditar núcleos familiares, alertas tempranas y doble rol.",
    description: "Gestión de acudientes con métricas de riesgo estudiantil, drawer de consulta multi-hijo, soporte para doble rol (Padre + Docente) y desactivación de cuentas con revocación de tokens.",
    roles: ["Directivo", "Padre de Familia"],
    dependsOn: ["01_autenticacion", "06_matriculas", "07_estudiantes_y_estados"],
    affects: ["18_gestion_traslados", "20_seguimiento_academico_directivo"],
    tables: ["padre_familia", "usuario", "detalle_padrefamilia"],
    rules: ["RN-GLOBAL-004", "RN-GLOBAL-007", "RN-GLOBAL-008", "RN-PAD-001 a RN-PAD-006"],
    hus: ["HU-PAD-001", "HU-PAD-002", "HU-PAD-003", "HU-PAD-004"],
    status: "CONSOLIDADO",
    connectionsCount: 11
  },
  "18_gestion_traslados": {
    id: "18_gestion_traslados",
    num: "18",
    name: "🔀 18. Gestión de Traslados",
    shortName: "Traslados",
    domain: "Admisión y Movilidad Estudiantil",
    icon: "ArrowLeftRight",
    purpose: "Gestionar traslados de matrícula entre colegios con consenso tripartito, verificación de cupos y emisión de informe parcial.",
    description: "Movilidad estudiantil interinstitucional e interna. Exige votos de colegio origen, colegio destino y acudiente (o bypass de Admin General), verifica cupos en destino, emite Informe Parcial de Calificaciones a la fecha de retiro (Dec. 1075 Art. 2.3.3.3.3.17) y ejecuta transacciones atómicas con Kysely.",
    roles: ["Directivo Origen", "Directivo Destino", "Padre de Familia", "Administrador General"],
    dependsOn: ["01_autenticacion", "02_gestion_colegios", "04_estructura_escolar", "06_matriculas", "07_estudiantes_y_estados", "14_cierre_y_boletines", "17_gestion_padres", "21_flujo_correos_y_verificaciones"],
    affects: ["06_matriculas", "07_estudiantes_y_estados", "11_calificaciones", "13_asistencia", "14_cierre_y_boletines"],
    tables: ["solicitud_traslado", "traslado_aprobacion", "matricula", "estudiante", "usuario_colegio", "detalle_padrefamilia"],
    rules: ["RN-GLOBAL-001", "RN-GLOBAL-006", "RN-GLOBAL-027", "RN-TRA-001 a RN-TRA-016", "Decreto 1075 Art. 2.3.3.3.3.17"],
    hus: ["HU-TRS-001", "HU-TRS-002", "HU-TRS-003", "HU-TRS-004"],
    status: "CONSOLIDADO",
    connectionsCount: 15
  },
  "19_seguimiento_y_promocion_academica": {
    id: "19_seguimiento_y_promocion_academica",
    num: "19",
    name: "🏅 19. Seguimiento y Promoción (Dec. 1290)",
    shortName: "Promoción Escolar",
    domain: "Evaluación Continua y Rendimiento",
    icon: "Award",
    purpose: "Consolidar el rendimiento anual y respaldar decisiones de promoción según el SIEE.",
    description: "Cálculo de promedios ponderados anuales, clasificación según materias reprobadas (APROBADO, PENDIENTE, NO_PROMOVIDO), graduación automática en grado terminal y advertencias no bloqueantes en matrícula.",
    roles: ["Directivo", "Comisión de Evaluación"],
    dependsOn: ["08_configuracion_academica", "11_calificaciones", "13_asistencia", "14_cierre_y_boletines"],
    affects: ["06_matriculas", "07_estudiantes_y_estados"],
    tables: ["decision_promocion_directivo", "registro_graduados", "resultado_academico", "matricula"],
    rules: ["RN-GLOBAL-034", "RN-PRO-001 a RN-PRO-006"],
    hus: ["HU-PRO-001", "HU-PRO-002", "HU-PRO-003", "HU-PRO-004"],
    status: "CONSOLIDADO",
    connectionsCount: 11
  },
  "20_seguimiento_academico_directivo": {
    id: "20_seguimiento_academico_directivo",
    num: "20",
    name: "👁️ 20. Seguimiento Directivo (Modo Espejo)",
    shortName: "Monitoreo Directivo",
    domain: "Auditoría, Gobernanza y Soporte",
    icon: "Eye",
    purpose: "Facilitar el acompañamiento pedagógico directivo en modo solo lectura estricto.",
    description: "Permite a los directivos emular la interfaz de profesores, alumnos y acudientes sin alterar tokens ni credenciales. Bloquea botones de edición, oculta gestión de traslados y despliega banner ámbar permanente.",
    roles: ["Directivo"],
    dependsOn: ["01_autenticacion", "03_usuarios_y_directivos", "05_docentes", "07_estudiantes_y_estados", "17_gestion_padres"],
    affects: ["11_calificaciones", "12_observaciones", "13_asistencia", "18_gestion_traslados"],
    tables: ["usuario", "docente", "estudiante", "padre_familia"],
    rules: ["RN-GLOBAL-029", "RN-SEG-001 a RN-SEG-012"],
    hus: ["HU-MON-001", "HU-MON-002", "HU-MON-003"],
    status: "CONSOLIDADO",
    connectionsCount: 12
  },
  "21_flujo_correos_y_verificaciones": {
    id: "21_flujo_correos_y_verificaciones",
    num: "21",
    name: "📧 21. Flujo de Correos y Verificaciones OTP",
    shortName: "Correos y OTP",
    domain: "Identidad, Seguridad y Acceso",
    icon: "MailCheck",
    purpose: "Centralizar la entrega SMTP, códigos OTP de 6 dígitos (15 min) y restablecimiento de claves.",
    description: "Motor transaccional de notificaciones. Genera códigos OTP numéricos para matrícula nueva y cambio de correo, valida caducidad y unicidad, y despacha credenciales docentes.",
    roles: ["Todos los Roles", "Público"],
    dependsOn: ["01_autenticacion"],
    affects: ["05_docentes", "06_matriculas", "18_gestion_traslados"],
    tables: ["codigo_verificacion_email", "password_reset_tokens", "usuario"],
    rules: ["RN-MAIL-001 a RN-MAIL-010"],
    hus: ["HU-OTP-001", "HU-OTP-002", "HU-OTP-003"],
    status: "CONSOLIDADO",
    connectionsCount: 11
  }
};

export const SYSTEM_METRICS: SystemMetrics = {
  totalModules: 21,
  totalTables: 62,
  totalGlobalRules: 34,
  totalAdrs: 11,
  totalDomains: 6,
  documentationCoveragePercent: 100,
  mostConnectedModules: [
    { name: "06. Matrículas e Inscripciones", id: "06_matriculas", count: 16 },
    { name: "05. Docentes y Asignación", id: "05_docentes", count: 15 },
    { name: "11. Calificaciones y Actividades", id: "11_calificaciones", count: 15 },
    { name: "01. Autenticación y Sesiones", id: "01_autenticacion", count: 14 },
    { name: "07. Estudiantes y Estados", id: "07_estudiantes_y_estados", count: 14 },
    { name: "08. Configuración Académica", id: "08_configuracion_academica", count: 14 },
    { name: "18. Gestión de Traslados", id: "18_gestion_traslados", count: 14 },
    { name: "04. Estructura Escolar", id: "04_estructura_escolar", count: 13 },
    { name: "14. Cierre y Boletines Oficiales", id: "14_cierre_y_boletines", count: 13 }
  ],
  domainDistribution: [
    { domain: "Identidad, Seguridad y Acceso", count: 3, color: "from-blue-600 to-indigo-600" },
    { domain: "Gobierno Institucional", count: 4, color: "from-purple-600 to-pink-600" },
    { domain: "Admisión y Movilidad Estudiantil", count: 4, color: "from-emerald-600 to-teal-600" },
    { domain: "Currículo y Calidad Pedagógica", count: 2, color: "from-amber-600 to-orange-600" },
    { domain: "Evaluación Continua y Rendimiento", count: 5, color: "from-cyan-600 to-blue-600" },
    { domain: "Auditoría, Gobernanza y Soporte", count: 3, color: "from-rose-600 to-red-600" }
  ]
};
