export { default as api, API_BASE_URL } from './api'
export { default as enrollmentService } from './enrollmentService'
export { default as gradesService } from './gradesService'
export { default as dbaService } from './dbaService'
export { default as academicService } from './academicService'
export { default as studentService } from './studentService'
export { default as parentService } from './parentService'
export { default as teacherService } from './teacherService'
export { default as socketService } from './socketService'
export { default as trasladoService } from './trasladoService'
export { default as reingresoService } from './reingresoService'
export { default as periodClosureService } from './periodClosureService'
export { default as boletinService } from './boletinService'
