export const MATRICULA_ESTADOS = {
  PENDIENTE: 'PENDIENTE',
  CORRECCION: 'CORRECCION',
  APROBADA: 'APROBADA',
  ACTIVA: 'ACTIVA',
  RECHAZADA: 'RECHAZADA',
  CANCELADA: 'CANCELADA',
  TRASLADADA: 'TRASLADADA',
  CULMINADA: 'CULMINADA'
} as const

export const TICKET_ESTADOS = {
  ABIERTO: 'ABIERTO',
  EN_PROCESO: 'EN_PROCESO',
  ESCALADO: 'ESCALADO',
  RESUELTO: 'RESUELTO'
} as const
