CREATE TABLE IF NOT EXISTS "auditoria_supervision" (
	"id_auditoria" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_admin_general" INTEGER NOT NULL,
	"id_colegio" INTEGER NOT NULL,
	"fecha_entrada" TIMESTAMPTZ NOT NULL,
	"fecha_salida" TIMESTAMPTZ NOT NULL,
	"id_directivo_aprobador" INTEGER NOT NULL,
	"motivo_auditoria" TEXT NOT NULL,
	"estado_auditoria" VARCHAR(50) NOT NULL,
	"fecha_solicitud" TIMESTAMPTZ NOT NULL,
	"tipo_auditoria" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_auditoria")
);




CREATE TABLE IF NOT EXISTS "auditoria_acciones_realizadas" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_auditoria" INTEGER NOT NULL,
	"fecha_accion" TIMESTAMPTZ NOT NULL,
	"modulo" VARCHAR(255) NOT NULL,
	"accion" VARCHAR(255) NOT NULL,
	"recurso_afectado" TEXT NOT NULL,
	"valor_antiguo" JSONB,
	"valor_nuevo" JSONB,
	"motivo_cambio" TEXT,
	PRIMARY KEY("id")
);

ALTER TABLE "auditoria_acciones_realizadas"
ADD FOREIGN KEY("id_auditoria") REFERENCES "auditoria_supervision"("id_auditoria")
